//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Popryzhenok.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public int ID { get; set; }
        public string FirstNane { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string NameCompany { get; set; }
        public string legalAddress { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string LogoImage { get; set; }
        public string PriorityInDelivery { get; set; }
        public string PointOfSale { get; set; }
        public string HistoryRealization { get; set; }
        public string TypeAgent { get; set; }
        public string Sale { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
