//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Popryzhenok.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryHistory
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string QuantityOfDeliveredGoods { get; set; }
    
        public virtual TypeSuppliers TypeSuppliers { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
