//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Popryzhenok.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string TypeMatetial { get; set; }
        public Nullable<int> SuppliersID { get; set; }
        public string MinimumQuantity { get; set; }
        public string Description { get; set; }
        public string Cost { get; set; }
        public string MainImagePath { get; set; }
        public string WareHouseHistoryCode { get; set; }
        public string Code { get; set; }
    
        public virtual WarehouseHistory WarehouseHistory { get; set; }
        public virtual Production Production { get; set; }
    }
}
