//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Popryzhenok.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tren2_SokolovEntities : DbContext
    {
        private static tren2_SokolovEntities _context;

        public tren2_SokolovEntities()
            : base("name=tren2_SokolovEntities")
        {
        }

        public static tren2_SokolovEntities GetContext()
        {
            if (_context == null)
                _context = new tren2_SokolovEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<DeliveryHistory> DeliveryHistory { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Production> Production { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductSale> ProductSale { get; set; }
        public virtual DbSet<QuantityOfGoods> QuantityOfGoods { get; set; }
        public virtual DbSet<StandardNumber> StandardNumber { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeAgent> TypeAgent { get; set; }
        public virtual DbSet<TypeOfRawMaterial> TypeOfRawMaterial { get; set; }
        public virtual DbSet<TypeSuppliers> TypeSuppliers { get; set; }
        public virtual DbSet<WarehouseHistory> WarehouseHistory { get; set; }
    }
}
