//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Popryzhenok.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSale
    {
        public int ID { get; set; }
        public string Products { get; set; }
        public string NameAgent { get; set; }
        public Nullable<System.DateTime> ImplementationDate { get; set; }
        public string NumberProducts { get; set; }
        public Nullable<int> ProductSaleID { get; set; }
    
        public virtual Products Products1 { get; set; }
    }
}
