//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Popryzhenok.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ProductSale = new HashSet<ProductSale>();
        }
    
        public string Article { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> MinimumProductCost { get; set; }
        public string length { get; set; }
        public string Width { get; set; }
        public string Height { get; set; }
        public string WeightWithPackaging { get; set; }
        public string WeightWithoutPackaging { get; set; }
        public string CertificateImage { get; set; }
        public string StandardNumberCode { get; set; }
        public string ProductionID { get; set; }
        public int ID { get; set; }
        public string ProductSaleCode { get; set; }
        public string TypeProduct { get; set; }
        public string RequiredNumberOfPeople { get; set; }
        public string WorkshopNumber { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Production Production { get; set; }
        public virtual StandardNumber StandardNumber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSale { get; set; }
    }
}
