//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Popryzhenok.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string CostPrice { get; set; }
        public string RequiredMaterials { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Material Material { get; set; }
        public virtual Products Products { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
